<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diazDeCerio" nsURI="http://www.example.org/diazDeCerio" nsPrefix="diazDeCerio">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PolygonList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="polygons" upperBound="-1"
        eType="#//Polygon" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment" eOpposite="#//Segment/polygon"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x2" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y2" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="polygon" lowerBound="1"
        eType="#//Polygon" eOpposite="#//Polygon/segments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Triangle" eSuperTypes="#//Polygon">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="figureMustBeClosed"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="figureMustBeClosed" value="&#xA;&#x9;&#x9;&#x9;let s1: Segment = self.segments->first() in&#xA;&#x9;&#x9;&#x9;let sn: Segment = self.segments->last() in&#xA;&#x9;&#x9;&#x9;s1.x1 = sn.x2 and s1.y1 = sn.y2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quadrilateral" eSuperTypes="#//Polygon"/>
  <eClassifiers xsi:type="ecore:EClass" name="Other" eSuperTypes="#//Polygon"/>
</ecore:EPackage>
